#!/usr/bin/env bash


msg="Some of the staged files contain flake8 errors.
You need to fix these errors before committing."

# All filenames that are staged and were added, copied, modified or renamed.
FILES=$(git diff --name-only --staged --diff-filter=ACMR)

changed_python_files=$(echo "$FILES" | grep ".py")
if [ -z "$changed_python_files" ]; then
  exit 0
fi

if ! flake8 "$changed_python_files" > /dev/null; then
  echo "$msg"
  exit 1
fi
