# Default configuration.

# The format of the times given in the table.
#
# Type: String in strftime format
time_format: "%H.%M"

# The names of the "headers" of the table.
#   Will be turned to all lowercase internally.
#
# Type: List of strings
header_identifier: [
  "montag - freitag",
  "samstag",
  "sonntag",
  "sonn- und feiertag",
]

# If a column does not hold any time data and begins with this identifier,
#   try to expand the given repeat interval.
# TODO: Explain this properly.
#
# Type: List of strings
repeat_identifier: [
  "alle",
]

# The minimum number of consecutive lines required, for something to be
#   recognized as a table.
#
# Type: int
min_table_rows: 5

# Which pages to consider for extraction. Defaults to 'all' for all pages.
# TODO: Extend to allow for ranges.
#
# Type: String of comma-separated ints or 'all'.
pages: "all"

# Maximum vertical distance in pixel between two rows, to be considered on
#   the same table. Basically checks if:
#     ((y_max of first row) - (y_min of second row)) <= max_row_distance
#
# Type: int
max_row_distance: 3
