# Default configuration.

# The format of the times given in the table.
#
# Type: String in strftime format
time_format: "%H.%M"

# The names of the "headers" of the table.
#   Will be turned to all lowercase internally.
#
# Type: List of strings
header_identifier: [
  "montag - freitag",
  "samstag",
  "sonntag",
  "sonn- und feiertag",
]

# If a column does not hold any time data and begins with this identifier,
#   try to expand the given repeat interval.
# Example: If a table contains a column (B) containing "Alle 5 min.",
#   this means between the times of the column left (A) and right (C) of B,
#   the times should be repeated every 5 minutes.
#
# Type: List of strings
repeat_identifier: [
  "alle",
]

# The minimum number of consecutive lines required, for something to be
#   recognized as a table.
#
# Type: int
min_table_rows: 5

# Which pages to consider for extraction. Defaults to 'all' for all pages.
#
# Type: String of comma-separated ints or ranges of ints, or 'all'.
# Example: "1-3,6,8-9" extracts the tables from the pages 1, 2, 3, 6, 8, 9.
pages: "all"

# Maximum vertical distance in pixel between two rows, to be considered on
#   the same table. Basically checks if:
#     ((y_max of first row) - (y_min of second row)) <= max_row_distance
#
# Type: int
max_row_distance: 3
