# Default configuration.

# The format of the times given in the table.
# See strftime for valid formats.
time_format: "%H.%M"

# The names of the "headers" of the table.
# List of strings. Will be turned to all lowercase internally.
header_identifier: [
  "montag - freitag",
  "samstag",
  "sonntag",
  "sonn- und feiertag",
]

# If a column does not hold any time data and begins with this identifier,
# try to expand the given repeat interval.
# TODO: Explain this properly.
repeat_identifier: [
  "alle",
]
