from test import P2GTestCase


class TestFieldContainer(P2GTestCase):
    def test_fields(self) -> None:
        ...

    def test_table(self) -> None:
        ...

    def test_has_type(self) -> None:
        ...

    def test_add_reference_to_field(self) -> None:
        ...

    def test_add_field(self) -> None:
        ...

    def test__add_field_at_index(self) -> None:
        ...

    def test_remove_field(self) -> None:
        ...

    def test_set_bbox_from_fields(self) -> None:
        ...

    def test__add_field(self) -> None:
        ...

    def test__contains_time_data(self) -> None:
        ...

    def test__split_at(self) -> None:
        ...

    def test_has_field_of_type(self) -> None:
        ...


class TestRow(P2GTestCase):
    def test_from_fields(self) -> None:
        ...

    def test_add_field(self) -> None:
        ...

    def test_y_distance(self) -> None:
        ...

    def test_type(self) -> None:
        ...

    def test_update_type(self) -> None:
        ...

    def test__detect_type(self) -> None:
        ...

    def test_split_at(self) -> None:
        ...


class TestColumn(P2GTestCase):
    def test_type(self) -> None:
        ...

    def test__detect_type(self) -> None:
        ...

    def test__get_repeat_intervals(self) -> None:
        ...

    def test_get_repeat_intervals(self) -> None:
        ...

    def test_merge(self) -> None:
        ...

    def test_add_field(self) -> None:
        ...

    def test_split_at(self) -> None:
        ...

    def test_from_field(self) -> None:
        ...

    def test_from_fields(self) -> None:
        ...
